name: Publish Docker Image

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      version:
        description: "PostgreSQL version to build"
        required: true
        default: "17"

env:
  IMAGE_NAME: tkahng/postgres

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push (multi-platform)
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            POSTGRES_VERSION=${{ github.event.inputs.version || '17' }}
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ github.event.inputs.version || '17' }}
